---
- name: Example playbook
  host: ubuntu
  become: ture
  become_method: sudo
        task:

        - name: Install multiple packages
        ansible.builtin.package:
          name: "{{item}}"
          state: present
        with_items:
        - apache2
        - telnet
        - unzip 