---
- name: User playbook
  host: amazon
  become: ture
  become_method: sudo
        task:

- name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
  ansible.builtin.user:
    name: johnd
    comment: John Doe
    group: wheel
...